spring:
  application:
    name: metamorfose-api

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: feijao
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: faalse

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.metamorfose: DEBUG
    sql: DEBUG
